# Generated by Django 5.2.9 on 2025-12-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BossSpiderTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Target domain for the spider.", max_length=255
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Target city for the spider.", max_length=100
                    ),
                ),
                ("count", models.IntegerField(help_text="Number of items to scrape.")),
                (
                    "query",
                    models.CharField(help_text="Query for the spider.", max_length=255),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Time when the task was created."
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Time when the task status was last updated.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                        ],
                        default="PENDING",
                        help_text="Current status of the task.",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="Result data returned by the spider (e.g., JSON).",
                    ),
                ),
                (
                    "exception",
                    models.TextField(
                        blank=True, help_text="Exception message if the task failed."
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID associated with this entry.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "boss_spider_task",
                "ordering": ["-create_time"],
            },
        ),
    ]
